{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "465a6f7e",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask, request, jsonify\n",
    "\n",
    "# Create Flask app\n",
    "app = Flask(__name__)\n",
    "\n",
    "# -----------------------------\n",
    "# Calculator API\n",
    "# -----------------------------\n",
    "@app.route(\"/\", methods=[\"POST\"])\n",
    "def calculator():\n",
    "\n",
    "    # Get JSON data from Postman\n",
    "    data = request.get_json()\n",
    "\n",
    "    # Validate request body\n",
    "    if not data:\n",
    "        return jsonify({\"error\": \"No JSON data received\"}), 400\n",
    "\n",
    "    num1 = data.get(\"num1\")\n",
    "    num2 = data.get(\"num2\")\n",
    "    operation = data.get(\"operation\")\n",
    "\n",
    "    # Validate input\n",
    "    if num1 is None or num2 is None or operation is None:\n",
    "        return jsonify({\"error\": \"num1, num2 and operation are required\"}), 400\n",
    "\n",
    "    # Perform calculation\n",
    "    if operation == \"add\":\n",
    "        result = num1 + num2\n",
    "\n",
    "    elif operation == \"sub\":\n",
    "        result = num1 - num2\n",
    "\n",
    "    elif operation == \"mul\":\n",
    "        result = num1 * num2\n",
    "\n",
    "    elif operation == \"div\":\n",
    "        if num2 == 0:\n",
    "            return jsonify({\"error\": \"Division by zero not allowed\"}), 400\n",
    "        result = num1 / num2\n",
    "\n",
    "    else:\n",
    "        return jsonify({\"error\": \"Invalid operation\"}), 400\n",
    "\n",
    "    # Return response\n",
    "    return jsonify({\n",
    "        \"num1\": num1,\n",
    "        \"num2\": num2,\n",
    "        \"operation\": operation,\n",
    "        \"result\": result\n",
    "    })\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# Health Check API\n",
    "# -----------------------------\n",
    "@app.route(\"/health\", methods=[\"GET\"])\n",
    "def health():\n",
    "    return jsonify({\n",
    "        \"status\": \"API is running\",\n",
    "        \"message\": \"Flask calculator API is healthy\"\n",
    "    })\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# Run Server\n",
    "# -----------------------------\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(host=\"127.0.0.1\", port=5000, debug=True)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
